<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="qasimsobeh-lt" name="CSVloginAndroid" tests="1" failures="1" timestamp="18 Dec 2017 19:45:51 GMT" time="9.619" errors="0">
  <testcase name="test" time="7.45" classname="automationAssignment.CSVloginAndroid">
    <failure type="com.experitest.client.InternalException" message="Exception caught while executing startLoggingDevice: Failed to start logging for device: Xiaomi Redmi 3S. see SeeTest log for details">
      <![CDATA[com.experitest.client.InternalException: Exception caught while executing startLoggingDevice: Failed to start logging for device: Xiaomi Redmi 3S. see SeeTest log for details
	at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:249)
	at com.experitest.client.Client.execute(Client.java:247)
	at com.experitest.client.Client.startLoggingDevice(Client.java:2266)
	at automationAssignment.CSVloginAndroid.loginTestAndroid(CSVloginAndroid.java:36)
	at automationAssignment.CSVloginAndroid.testAux(CSVloginAndroid.java:26)
	at automationAssignment.BaseTest.test(BaseTest.java:120)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- CSVloginAndroid -->
